### ISSUE TITLE
rootns nicht 100% funktionsfähig

### ISSUE THREAD

**Issue by chhe-01** [cziehr/dokuwiki-plugin-namespacemessage#1]
Hallo,

Wenn ich den Hinweis auf der Startseite ausblenden möchte habe ich folgende Eingaben in der Konfiguration getestet:

`rootns, lokal`
=> Hinweis bleibt auf Startseite bestehen. Im "Lokal Bereich" wird er ausgeblendet.

`lokal, rootns`
=> Hinweis auf Startseite verschwindet. Im "lokal Bereich" erscheint er.

Wie kann ich den Hinweis sowohl im gesamten lokalen Bereich als auch auf der Startseite ausblenden?

**Comment by cziehr** [comment]
Zum Trennen der Namensräume wird nur ein Leerzeichen, aber kein Komma verwendet. Ohne Komma sollte es funktionieren.

**Comment by chhe-01** [comment]
Danke für diesen Hinweis.... 
Den entsprechenden Infosatz in der Konfiguration habe ich gesehen, offensichtlich aber nicht genau genug gelesen....
